---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgres
  name: argo-postgres-config
  namespace: argo
stringData:
  password: password
  username: postgres
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: argo-server-sso
  namespace: argo
stringData:
  clientID: argo-server
  clientSecret: <secret-in-plain-text>

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: argo-workflows-webhook-clients
# stringData:
#   bitbucket.org: |
#     type: bitbucket
#     secret: "my-uuid"
#   bitbucketserver: |
#     type: bitbucketserver
#     secret: "shh!"
#   github.com: |
#     type: github
#     secret: "shh!"
#   gitlab.com: |-
#     type: gitlab
#     secret: "shh!"
    
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   labels:
#     app: minio
#   name: my-minio-cred
# stringData:
#   accesskey: admin
#   secretkey: password
# type: Opaque